### ISSUE TITLE
Gateway transactions still show as pending despite succeeding

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/frontends#26]
**Describe the bug**
Deposits of ETH to L2 Kovan using the gateway are listed as Pending in the `txs` page,  despite succeeding and receiving the ETH on L2.

**To Reproduce**
1. Deposit ETH to L2 Kovan
2. Wait for L2 ETH balance to update on the UI card on the same page.
3. Once deposit has succeeded and your L2 balance has updated, visit the `txs` page.
4. See your recent deposit transaction status as "Pending"

**Expected behavior**
Status for txns should be updated to "Completed" once the L2 balance has been updated.

**Comment by K-Ho** [comment]
Most likely just issues with the graph
