### ISSUE TITLE
Gateway UI Failing on L2

### ISSUE THREAD

**Issue by vintrocode** [ethereum-optimism/frontends#33]
The gateway UI (https://gateway.optimism.io/) errors when trying to switch to layer 2 in a few ways:

Setup:
Go to the gateway site, connect metamask to Kovan.

Path 1: clicking on the "switch to layer 2" button fails.
Path 2. disconnecting wallet from gateway, connecting metamask to Kovan L2, clicking the connect button again, and clicking the "withdraw" button fails.

Kovan L2 Network Config:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/77507980/115966792-034feb00-a4e4-11eb-847a-0cb7187c79df.png">
(nice)

I was successfully able to deposit funds to L2, I just can't connect to L2 to view or withdraw them. I didn't have any particular goal in mind other than to just test it out for myself.
<img width="2549" alt="Screen Shot 2021-04-23 at 4 37 37 PM" src="https://user-images.githubusercontent.com/77507980/115966757-e1566880-a4e3-11eb-9deb-02db83838c79.png">

**Comment by snario** [comment]
Can you provide another reproduction case for "Path 1: clicking on the "switch to layer 2" button fails."; for me when loading the page, while connected to Kovan, then clicking that button, opens a popup to switch the network on MetaMask which when accepted does switch the network and the UI updates.

**Comment by vintrocode** [comment]
this might explain better.

https://user-images.githubusercontent.com/77507980/116139544-fae5e480-a68a-11eb-8f1f-d3ced9a567c8.mov

**Comment by gigamesh** [comment]
@vintrocode big thanks for posting the issue!

What browser are you using? 
Are there any errors in the console?

**Comment by vintrocode** [comment]
@gigamesh I'm using Firefox
There was an error in the console:
```
MetaMask - RPC Error: The method 'wallet_addEthereumChain' does not exist / is not available. 
Object { code: -32601, message: "The method 'wallet_addEthereumChain' does not exist / is not available.", data: {…} }
​
code: -32601
​
data: Object { method: "wallet_addEthereumChain", jsonrpc: "2.0", id: 1938585911, … }
​
message: "The method 'wallet_addEthereumChain' does not exist / is not available."
​
<prototype>: Object { … }
inpage.js:1:26889
    createErrorMiddleware moz-extension://ee6f8955-ff49-b64d-a1be-c9d1caca98ab/inpage.js:1
    _runReturnHandlers moz-extension://ee6f8955-ff49-b64d-a1be-c9d1caca98ab/inpage.js:15
    _runReturnHandlers moz-extension://ee6f8955-ff49-b64d-a1be-c9d1caca98ab/inpage.js:15
    _processRequest moz-extension://ee6f8955-ff49-b64d-a1be-c9d1caca98ab/inpage.js:15
```

**Comment by vintrocode** [comment]
i'm not experiencing this issue anymore, some recent update must have resolved it. thanks
