### ISSUE TITLE
Update Roadmap to proper date

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/frontends#40]
**Describe the bug**
On https://optimism.io roadmap still says that we need to complete our hackathon testnet, which is set to launch APR 2021:

<img width="1023" alt="Screen Shot 2021-05-06 at 2 39 37 PM" src="https://user-images.githubusercontent.com/37757724/117356005-e36fde00-ae78-11eb-8cb4-8eec90a423a4.png">

Since we're now in MAY 2021, I think we should update the roadmap so that there isn't any confusion.

**Comment by gigamesh** [comment]
The hackathon was in april, so I think for most observers this will make sense don't you think?

**Comment by Jinglan** [comment]
Let's just take it down for now, we have the new website design coming soon
