### ISSUE TITLE
Improve status page communication

### ISSUE THREAD

**Issue by gigamesh** [ethereum-optimism/frontends#41]
Problem: Users are seeing the sad emojis and thinking that the sequencer is down when only the batch submitter is. 

Proposed solution:
Separate the two statuses so that the big emoji only corresponds to the sequencer, and a note below the divider (maybe prepended with a 🔴 ) to communicate the batch submitter status. 

Also, replace the text emojis with PNGs of them (not all emojis are supported on all browsers)

**Comment by smartcontracts** [comment]
Yeah ideally we would have separate status indicators for each individual service
