### ISSUE TITLE
Link to `optimism-tutorial` is broken

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/frontends#47]
**Describe the bug**
This issue was raised by @qbzzt in https://github.com/ethereum-optimism/optimism-tutorial/issues/33.

Copy/pasted the issue here below for quick reference:

> **To Reproduce**
> 
> 1. Go to [the homepage](https://optimism.io/) 
> 2.  Click **DEVELOPERS > Tutorial**
> 3. See the 404 error
>
> **Expected behavior**
>
> I'd expect the link to lead to this tutorial.
>
> **Screenshots**
>
> ![tutorial_404](https://user-images.githubusercontent.com/12722969/118297704-2139bb80-b4a4-11eb-8235-aaa3afd5fe7e.png)

**Comment by gigamesh** [comment]
fixed!
