### ISSUE TITLE
Small typo in Optimistic Kovan network name

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/frontends#54]
**Describe the bug**
The network name of Optimistic Kovan is shown as `Kovan Optimistim` when it should read `Optimistic Kovan` (following the convention laid out by @smartcontracts in the recent update to the community hub: https://community.optimism.io/docs/developers/networks.html).

**To Reproduce**
1. Git clone this repo: `git clone https://github.com/ethereum-optimism/frontends.git`
2. Checkout recent working branch and install deps: `git checkout feat/gateway-tokenlist-support && yarn`
3. Start gateway: `yarn start:gateway`
4. Go to https://localhost:3000
5. Connect your MetaMask wallet to L1 Kovan
6. Click the deposit-withdrawal toggle switch to switch to request to switch to Optimistic Kovan.
7. Confirm the new network
8. See typo in red network name:

<img width="1021" alt="Screen Shot 2021-05-23 at 8 26 22 PM" src="https://user-images.githubusercontent.com/37757724/119284351-2534ae80-bc05-11eb-8f89-0e933568994d.png">

**System Specs:**
 - OS: macOS, 16 inch MacBook Pro

**Comment by smartcontracts** [comment]
This is my favorite new convention.

**Comment by gigamesh** [comment]
Optimyst

**Comment by gigamesh** [comment]
fixed in the token list PR: https://github.com/ethereum-optimism/frontends/pull/46
