### ISSUE TITLE
L1 ETH balances do not update

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/frontends#56]
**Describe the bug**
On the [gateway](https://deploy-preview-46--optimism-gateway.netlify.app/), the UI will never show pre-existing balances.
However, when making an L2 Kovan withdrawal, you can see the L2 Kovan ETH balance decrease while the L1 balance remains unchanged.

**To Reproduce**
1. Go to https://deploy-preview-46--optimism-gateway.netlify.app/
5. Connect your MetaMask wallet to L2 Kovan
6. Initiate an L2 withdrawal 
7. See L2 balance decrease and L1 balance unchanged

**Expected behavior**
* L1 ETH balance should show pre-existing balance
* L1 balance should update after L2 withdrawals

**System Specs:**
 - OS: macOS, 16 inch MacBook Pro

**Additional context**
Likely related to #55

**Comment by platocrat** [comment]
The above issue was first seen locally, however, I just used the Netlify hosted gateway and still see the same issues for L1 balances, namely: 
1. pre-existing L1 balances are never properly displayed
2. after making an L2 withdrawal, L2 balance updates but L1 balance remains unchanged (at 0, since pre-existing balances are ignored).

**Comment by gigamesh** [comment]
hmm - the L1 balance not updating after a withdrawal is because there is something wrong with the message relayer (Kelvin submitted a PR to fix it), but I can't reproduce the problem of ETH L1 balance not loading. This is on Chrome?

**Comment by platocrat** [comment]
> hmm - the L1 balance not updating after a withdrawal is because there is something wrong with the message relayer (Kelvin submitted a PR to fix it), but I can't reproduce the problem of ETH L1 balance not loading. This is on Chrome?

Yeah, this is on Chrome and Brave for me.

**Comment by platocrat** [comment]
resolved in #46
